name: flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.4.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  exif: ^1.0.3
  flutter_form_builder: ^4.2.0
  flutter_lock_screen: ^1.0.8
  flutter_swiper: ^1.1.6
  geolocator: ^6.2.0
  google_fonts: ^1.0.0
  dio_http_cache: ^0.2.11
  image_picker: ^0.6.7+22
  imei_plugin: ^1.2.0
  infinity_page_view: ^1.0.0
  local_auth: ^0.6.3+4
  location_permissions: any
  path_provider: ^2.0.1
  permission_handler: any
  pin_code_fields: ^7.0.0
  shared_preferences: ^2.0.3
  splashscreen: ^1.3.5
  toast: ^0.1.5
  connectivity_plus: ^0.8.1
  hooks_riverpod: ^0.12.4
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0

flutter:


  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
